CREATE TABLE TEST (
    id VARCHAR2(10) NOT NULL,
    name VARCHAR2(10) NOT NULL,
    age NUMBER(3) NOT NULL
);

INSERT INTO TEST (id, name, age) VALUES('00001', 'TEST_NAME', 10);
INSERT INTO TEST (id, name, age) VALUES('00002', 'TEST_NAME2', 20);
